version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      myst:
        patterns: ["mystmd", "@myst-theme/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
